import { AgentConfig } from '../models/agent.model';

/**
 * Compiles the reactive AgentConfig state into a clean, formatted Markdown document
 * adapted to the selected AI assistant target format (.cursorrules, AGENTS.md, etc.).
 */
export function compileAgentMarkdown(config: AgentConfig): string {
  const isEn = config.outputLanguage === 'en';
  const lines: string[] = [];

  // File header banner
  lines.push(`<!-- Generated by AgentCraft Studio | Target: ${config.targetFormat} -->`);
  lines.push(`# ${config.projectName.trim() || (isEn ? 'Agent Guidelines' : 'Directivas del Agente')}`);

  if (config.description.trim()) {
    lines.push('');
    lines.push(`> ${config.description.trim()}`);
  }

  // Persona / Role
  if (config.role.trim()) {
    lines.push('');
    lines.push(`## ${isEn ? 'Role & Persona' : 'Rol y Personalidad'}`);
    lines.push(config.role.trim());
  }

  // Tech Stack
  if (config.techStack.length > 0) {
    lines.push('');
    lines.push(`## ${isEn ? 'Technology Stack' : 'Stack Tecnológico'}`);
    for (const tech of config.techStack) {
      lines.push(`- ${tech}`);
    }
  }

  // Architecture & Guidelines
  if (config.architecturalRules.length > 0) {
    lines.push('');
    lines.push(`## ${isEn ? 'Directives & Architecture' : 'Directivas y Reglas de Arquitectura'}`);
    for (const rule of config.architecturalRules) {
      lines.push(`- ${rule}`);
    }
  }

  // Git Conventions & Workflow
  if (config.gitConvention.trim()) {
    lines.push('');
    lines.push(`## ${isEn ? 'Git Workflow & Conventions' : 'Flujo de Trabajo y Convenciones Git'}`);
    lines.push(`- ${config.gitConvention.trim()}`);
  }

  // Custom Instructions & Boundaries
  if (config.customInstructions.trim()) {
    lines.push('');
    lines.push(`## ${isEn ? 'Custom Instructions & Boundaries' : 'Instrucciones Libres y Restricciones'}`);
    lines.push(config.customInstructions.trim());
  }

  return lines.join('\n');
}
