import { AgentConfig } from '../models/agent.model';
import en from '../i18n/translations/en.json';
import es from '../i18n/translations/es.json';

export function formatRuleItem(rule: string): string {
  const trimmed = rule.trim();
  if (!trimmed) return '';
  const clean = trimmed.replace(/^-\s*/, '');
  return `- ${clean}`;
}

export function formatNeverItem(rule: string): string {
  const trimmed = rule.trim();
  if (!trimmed) return '';
  return trimmed.replace(/^-\s*/, '');
}

export function compileAgentMarkdown(config: AgentConfig): string {
  const isEn = config.outputLanguage === 'en';
  const isAgentsMd = config.targetFormat === 'agents';
  const isCursor = config.targetFormat === 'cursor';
  const t = (isEn ? en : es).compiler;
  const lines: string[] = [];

  if (isCursor) {
    lines.push('---');
    lines.push(`description: ${config.description.trim() || config.projectName.trim()}`);
    lines.push('globs: *');
    lines.push('---');
    lines.push('');
  }

  lines.push(`<!-- Generated by AgentCraft Studio | Target: ${config.targetFormat} -->`);
  const projectTitle = config.projectName.trim() || t.defaultTitle;
  lines.push(`# ${isAgentsMd ? `${t.titlePrefix} ${projectTitle}` : projectTitle}`);

  if (config.description.trim()) {
    lines.push('');
    lines.push(`> ${config.description.trim()}`);
  }

  let sectionIndex = 0;
  const nextSectionPrefix = (): string => (isAgentsMd ? `${++sectionIndex}. ` : '');

  if (isAgentsMd && config.description.trim()) {
    lines.push('', `## ${nextSectionPrefix()}${t.projectVision}`, config.description.trim());
    if (config.role.trim()) {
      lines.push('', `**${t.assignedRole}:** ${config.role.trim()}`);
    }
  } else if (config.role.trim()) {
    lines.push('', `## ${t.assignedRole}`, config.role.trim());
  }

  const toneMap: Record<string, string> = {
    concise: t.toneConciseValue,
    balanced: t.toneBalancedValue,
    explanatory: t.toneExplanatoryValue,
  };
  const autonomyMap: Record<string, string> = {
    conservative: t.autonomyConservativeValue,
    collaborative: t.autonomyCollaborativeValue,
    autonomous: t.autonomyAutonomousValue,
  };

  const hasTone = Boolean(config.tone && toneMap[config.tone]);
  const hasAutonomy = Boolean(config.autonomy && autonomyMap[config.autonomy]);
  const hasCommRules = Boolean(config.communicationRules && config.communicationRules.length > 0);
  const hasCustomTone = Boolean(config.customTone?.trim());

  if (hasTone || hasAutonomy || hasCommRules || hasCustomTone) {
    lines.push('', `## ${nextSectionPrefix()}${t.personaToneTitle}`);
    if (hasTone) {
      lines.push(`- **${t.toneLabel}:** ${toneMap[config.tone]}`);
    }
    if (hasAutonomy) {
      lines.push(`- **${t.autonomyLabel}:** ${autonomyMap[config.autonomy]}`);
    }
    if (hasCommRules) {
      lines.push(`- **${t.commRulesLabel}:**`);
      config.communicationRules.forEach((rule) => lines.push(`  - ${rule}`));
    }
    if (hasCustomTone) {
      lines.push(`- **${t.customToneLabel}:** ${config.customTone.trim()}`);
    }
  }

  if (config.techStack.length > 0) {
    lines.push('', `## ${nextSectionPrefix()}${t.techStack}`);
    for (const tech of config.techStack) lines.push(`- ${tech}`);
  }

  if (config.architecturalRules.length > 0) {
    lines.push('', `## ${nextSectionPrefix()}${t.architecture}`);
    config.architecturalRules.forEach((r) => lines.push(formatRuleItem(r)));
  }

  if (config.uiDesignRules && config.uiDesignRules.length > 0) {
    lines.push('', `## ${nextSectionPrefix()}${t.uiDesign}`);
    config.uiDesignRules.forEach((r) => lines.push(formatRuleItem(r)));
  }

  const hasGit = Boolean(config.gitConvention.trim());
  const hasCmds = Boolean(config.buildCommands?.build || config.buildCommands?.test || config.buildCommands?.dev);
  const hasProposeCommit = Boolean(config.proposeCommit);

  if (hasGit || hasCmds || hasProposeCommit) {
    lines.push('', `## ${nextSectionPrefix()}${t.gitWorkflow}`);
    if (hasGit) {
      const isConv = /conventional/i.test(config.gitConvention);
      if (isConv) {
        lines.push(
          `- **${t.gitStandard}:** ${t.gitStandardValue}`,
          `- **${t.gitStructure}:** ${t.gitStructureValue}`,
        );
      } else {
        lines.push(`- **${t.gitConvention}:** ${config.gitConvention.trim()}`);
      }
    }

    if (hasProposeCommit) {
      lines.push(`- **${t.gitDelivery}:** ${t.gitDeliveryValue}`);
    }

    if (hasCmds) {
      lines.push('', `### ${t.commandsTitle}`, '```bash');
      if (config.buildCommands.build) lines.push(`# ${t.buildComment}`, config.buildCommands.build);
      if (config.buildCommands.test) lines.push(`# ${t.testComment}`, config.buildCommands.test);
      if (config.buildCommands.dev) lines.push(`# ${t.devComment}`, config.buildCommands.dev);
      lines.push('```');
    }
  }

  const hasNeverRules = Boolean(config.neverRules && config.neverRules.length > 0);
  const hasCustomInst = Boolean(config.customInstructions.trim());

  if (hasNeverRules || hasCustomInst) {
    lines.push('', `## ${nextSectionPrefix()}${t.instructionsTitle}`);
    if (hasNeverRules) {
      lines.push('', `### 🚫 ${t.neverTitle}`);
      for (const rule of config.neverRules) {
        lines.push(`- ❌ ${formatNeverItem(rule)}`);
      }
    }
    if (hasCustomInst) {
      if (hasNeverRules) {
        lines.push('', `### ${t.additionalInstructionsTitle}`);
      }
      lines.push(config.customInstructions.trim());
    }
  }

  return lines.join('\n');
}
